name: Python CI

on:
  workflow_dispatch:
  push: 
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      #pull le depot   uses-> utiliser une action créer par quelqu'un d'autres
      - uses: actions/checkout@v3
      - name: Print folder
        run: |
          ls
