name: Python CI

on:
  workflow_dispatch:
  push: 
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      #pull le depot   uses-> utiliser une action créer par quelqu'un d'autres
      - uses: actions/checkout@v3
      
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Intall requirements
        run: |
          python -m pip install -r requirements.txt

      - name: Run Pytest
        run: |
          python -m pytest
        
      - name: Run Pylint
        run: |
          pylint application/ tests/


